// Code generated by go-swagger; DO NOT EDIT.

package policy_decisions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new policy decisions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for policy decisions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetDecisionByIDUsingGET2(params *GetDecisionByIDUsingGET2Params, opts ...ClientOption) (*GetDecisionByIDUsingGET2OK, error)

	GetDecisionsUsingGET2(params *GetDecisionsUsingGET2Params, opts ...ClientOption) (*GetDecisionsUsingGET2OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetDecisionByIDUsingGET2 returns a policy decision by id

Find a specific policy decision based on the input policy decision id.
*/
func (a *Client) GetDecisionByIDUsingGET2(params *GetDecisionByIDUsingGET2Params, opts ...ClientOption) (*GetDecisionByIDUsingGET2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDecisionByIDUsingGET2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "getDecisionByIdUsingGET_2",
		Method:             "GET",
		PathPattern:        "/policy/api/policyDecisions/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDecisionByIDUsingGET2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDecisionByIDUsingGET2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDecisionByIdUsingGET_2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetDecisionsUsingGET2 fetches a list of policy decisions

Returns a paginated list of policy decisions. If a dryRunId is provided, the return value has a field indicating whether the dry run is complete.
*/
func (a *Client) GetDecisionsUsingGET2(params *GetDecisionsUsingGET2Params, opts ...ClientOption) (*GetDecisionsUsingGET2OK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDecisionsUsingGET2Params()
	}
	op := &runtime.ClientOperation{
		ID:                 "getDecisionsUsingGET_2",
		Method:             "GET",
		PathPattern:        "/policy/api/policyDecisions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDecisionsUsingGET2Reader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDecisionsUsingGET2OK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDecisionsUsingGET_2: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
