// Code generated by go-swagger; DO NOT EDIT.

package custom_naming

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// CreateCustomNameReader is a Reader for the CreateCustomName structure.
type CreateCustomNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCustomNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateCustomNameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCustomNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCustomNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCustomNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCustomNameCreated creates a CreateCustomNameCreated with default headers values
func NewCreateCustomNameCreated() *CreateCustomNameCreated {
	return &CreateCustomNameCreated{}
}

/* CreateCustomNameCreated describes a response with status code 201, with default header values.

successful operation
*/
type CreateCustomNameCreated struct {
	Payload *models.CustomNaming
}

func (o *CreateCustomNameCreated) Error() string {
	return fmt.Sprintf("[POST /iaas/api/naming][%d] createCustomNameCreated  %+v", 201, o.Payload)
}
func (o *CreateCustomNameCreated) GetPayload() *models.CustomNaming {
	return o.Payload
}

func (o *CreateCustomNameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomNaming)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomNameBadRequest creates a CreateCustomNameBadRequest with default headers values
func NewCreateCustomNameBadRequest() *CreateCustomNameBadRequest {
	return &CreateCustomNameBadRequest{}
}

/* CreateCustomNameBadRequest describes a response with status code 400, with default header values.

Invalid Request - bad data
*/
type CreateCustomNameBadRequest struct {
	Payload *models.Error
}

func (o *CreateCustomNameBadRequest) Error() string {
	return fmt.Sprintf("[POST /iaas/api/naming][%d] createCustomNameBadRequest  %+v", 400, o.Payload)
}
func (o *CreateCustomNameBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCustomNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomNameForbidden creates a CreateCustomNameForbidden with default headers values
func NewCreateCustomNameForbidden() *CreateCustomNameForbidden {
	return &CreateCustomNameForbidden{}
}

/* CreateCustomNameForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateCustomNameForbidden struct {
	Payload *models.ServiceErrorResponse
}

func (o *CreateCustomNameForbidden) Error() string {
	return fmt.Sprintf("[POST /iaas/api/naming][%d] createCustomNameForbidden  %+v", 403, o.Payload)
}
func (o *CreateCustomNameForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *CreateCustomNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCustomNameNotFound creates a CreateCustomNameNotFound with default headers values
func NewCreateCustomNameNotFound() *CreateCustomNameNotFound {
	return &CreateCustomNameNotFound{}
}

/* CreateCustomNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateCustomNameNotFound struct {
	Payload *models.Error
}

func (o *CreateCustomNameNotFound) Error() string {
	return fmt.Sprintf("[POST /iaas/api/naming][%d] createCustomNameNotFound  %+v", 404, o.Payload)
}
func (o *CreateCustomNameNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCustomNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
