// Code generated by go-swagger; DO NOT EDIT.

package fabric_azure_disk_encryption_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new fabric azure disk encryption sets API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for fabric azure disk encryption sets API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetAzureDiskEncryptionSets(params *GetAzureDiskEncryptionSetsParams, opts ...ClientOption) (*GetAzureDiskEncryptionSetsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetAzureDiskEncryptionSets gets azure disk encryption sets

  Get all Azure disk encryption sets
*/
func (a *Client) GetAzureDiskEncryptionSets(params *GetAzureDiskEncryptionSetsParams, opts ...ClientOption) (*GetAzureDiskEncryptionSetsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAzureDiskEncryptionSetsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getAzureDiskEncryptionSets",
		Method:             "GET",
		PathPattern:        "/iaas/api/fabric-azure-disk-encryption-sets",
		ProducesMediaTypes: []string{"app/json", "application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetAzureDiskEncryptionSetsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetAzureDiskEncryptionSetsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getAzureDiskEncryptionSets: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
