// Code generated by go-swagger; DO NOT EDIT.

package deployment_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewSubmitResourceActionRequestUsingPOSTParams creates a new SubmitResourceActionRequestUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubmitResourceActionRequestUsingPOSTParams() *SubmitResourceActionRequestUsingPOSTParams {
	return &SubmitResourceActionRequestUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubmitResourceActionRequestUsingPOSTParamsWithTimeout creates a new SubmitResourceActionRequestUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewSubmitResourceActionRequestUsingPOSTParamsWithTimeout(timeout time.Duration) *SubmitResourceActionRequestUsingPOSTParams {
	return &SubmitResourceActionRequestUsingPOSTParams{
		timeout: timeout,
	}
}

// NewSubmitResourceActionRequestUsingPOSTParamsWithContext creates a new SubmitResourceActionRequestUsingPOSTParams object
// with the ability to set a context for a request.
func NewSubmitResourceActionRequestUsingPOSTParamsWithContext(ctx context.Context) *SubmitResourceActionRequestUsingPOSTParams {
	return &SubmitResourceActionRequestUsingPOSTParams{
		Context: ctx,
	}
}

// NewSubmitResourceActionRequestUsingPOSTParamsWithHTTPClient creates a new SubmitResourceActionRequestUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubmitResourceActionRequestUsingPOSTParamsWithHTTPClient(client *http.Client) *SubmitResourceActionRequestUsingPOSTParams {
	return &SubmitResourceActionRequestUsingPOSTParams{
		HTTPClient: client,
	}
}

/* SubmitResourceActionRequestUsingPOSTParams contains all the parameters to send to the API endpoint
   for the submit resource action request using p o s t operation.

   Typically these are written to a http.Request.
*/
type SubmitResourceActionRequestUsingPOSTParams struct {

	/* ActionRequest.

	   actionRequest
	*/
	ActionRequest *models.ResourceActionRequest

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). If you do not specify explicitly an exact version, you will be calling the latest supported API version.
	*/
	APIVersion *string

	/* DeploymentID.

	   Deployment ID

	   Format: uuid
	*/
	DeploymentID strfmt.UUID

	/* ResourceID.

	   Resource ID

	   Format: uuid
	*/
	ResourceID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the submit resource action request using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitResourceActionRequestUsingPOSTParams) WithDefaults() *SubmitResourceActionRequestUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the submit resource action request using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitResourceActionRequestUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithTimeout(timeout time.Duration) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithContext(ctx context.Context) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithHTTPClient(client *http.Client) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActionRequest adds the actionRequest to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithActionRequest(actionRequest *models.ResourceActionRequest) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetActionRequest(actionRequest)
	return o
}

// SetActionRequest adds the actionRequest to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetActionRequest(actionRequest *models.ResourceActionRequest) {
	o.ActionRequest = actionRequest
}

// WithAPIVersion adds the aPIVersion to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithAPIVersion(aPIVersion *string) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithDeploymentID adds the deploymentID to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithDeploymentID(deploymentID strfmt.UUID) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetDeploymentID(deploymentID)
	return o
}

// SetDeploymentID adds the deploymentId to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetDeploymentID(deploymentID strfmt.UUID) {
	o.DeploymentID = deploymentID
}

// WithResourceID adds the resourceID to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) WithResourceID(resourceID strfmt.UUID) *SubmitResourceActionRequestUsingPOSTParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the submit resource action request using p o s t params
func (o *SubmitResourceActionRequestUsingPOSTParams) SetResourceID(resourceID strfmt.UUID) {
	o.ResourceID = resourceID
}

// WriteToRequest writes these params to a swagger request
func (o *SubmitResourceActionRequestUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ActionRequest != nil {
		if err := r.SetBodyParam(o.ActionRequest); err != nil {
			return err
		}
	}

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}

	// path param deploymentId
	if err := r.SetPathParam("deploymentId", o.DeploymentID.String()); err != nil {
		return err
	}

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
