// Code generated by go-swagger; DO NOT EDIT.

package catalog_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewPublishCatalogItemParams creates a new PublishCatalogItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublishCatalogItemParams() *PublishCatalogItemParams {
	return &PublishCatalogItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublishCatalogItemParamsWithTimeout creates a new PublishCatalogItemParams object
// with the ability to set a timeout on a request.
func NewPublishCatalogItemParamsWithTimeout(timeout time.Duration) *PublishCatalogItemParams {
	return &PublishCatalogItemParams{
		timeout: timeout,
	}
}

// NewPublishCatalogItemParamsWithContext creates a new PublishCatalogItemParams object
// with the ability to set a context for a request.
func NewPublishCatalogItemParamsWithContext(ctx context.Context) *PublishCatalogItemParams {
	return &PublishCatalogItemParams{
		Context: ctx,
	}
}

// NewPublishCatalogItemParamsWithHTTPClient creates a new PublishCatalogItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublishCatalogItemParamsWithHTTPClient(client *http.Client) *PublishCatalogItemParams {
	return &PublishCatalogItemParams{
		HTTPClient: client,
	}
}

/*
PublishCatalogItemParams contains all the parameters to send to the API endpoint

	for the publish catalog item operation.

	Typically these are written to a http.Request.
*/
type PublishCatalogItemParams struct {

	/* Request.

	   request
	*/
	Request *models.CatalogItemPublishRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the publish catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishCatalogItemParams) WithDefaults() *PublishCatalogItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the publish catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishCatalogItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the publish catalog item params
func (o *PublishCatalogItemParams) WithTimeout(timeout time.Duration) *PublishCatalogItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the publish catalog item params
func (o *PublishCatalogItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the publish catalog item params
func (o *PublishCatalogItemParams) WithContext(ctx context.Context) *PublishCatalogItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the publish catalog item params
func (o *PublishCatalogItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the publish catalog item params
func (o *PublishCatalogItemParams) WithHTTPClient(client *http.Client) *PublishCatalogItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the publish catalog item params
func (o *PublishCatalogItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the publish catalog item params
func (o *PublishCatalogItemParams) WithRequest(request *models.CatalogItemPublishRequest) *PublishCatalogItemParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the publish catalog item params
func (o *PublishCatalogItemParams) SetRequest(request *models.CatalogItemPublishRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PublishCatalogItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
