// Code generated by go-swagger; DO NOT EDIT.

package catalog_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewRepublishCatalogItemParams creates a new RepublishCatalogItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRepublishCatalogItemParams() *RepublishCatalogItemParams {
	return &RepublishCatalogItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRepublishCatalogItemParamsWithTimeout creates a new RepublishCatalogItemParams object
// with the ability to set a timeout on a request.
func NewRepublishCatalogItemParamsWithTimeout(timeout time.Duration) *RepublishCatalogItemParams {
	return &RepublishCatalogItemParams{
		timeout: timeout,
	}
}

// NewRepublishCatalogItemParamsWithContext creates a new RepublishCatalogItemParams object
// with the ability to set a context for a request.
func NewRepublishCatalogItemParamsWithContext(ctx context.Context) *RepublishCatalogItemParams {
	return &RepublishCatalogItemParams{
		Context: ctx,
	}
}

// NewRepublishCatalogItemParamsWithHTTPClient creates a new RepublishCatalogItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewRepublishCatalogItemParamsWithHTTPClient(client *http.Client) *RepublishCatalogItemParams {
	return &RepublishCatalogItemParams{
		HTTPClient: client,
	}
}

/*
RepublishCatalogItemParams contains all the parameters to send to the API endpoint

	for the republish catalog item operation.

	Typically these are written to a http.Request.
*/
type RepublishCatalogItemParams struct {

	/* CatalogItemID.

	   Catalog Item ID

	   Format: uuid
	*/
	CatalogItemID strfmt.UUID

	/* Request.

	   request
	*/
	Request *models.CatalogItemPublishRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the republish catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepublishCatalogItemParams) WithDefaults() *RepublishCatalogItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the republish catalog item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RepublishCatalogItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the republish catalog item params
func (o *RepublishCatalogItemParams) WithTimeout(timeout time.Duration) *RepublishCatalogItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the republish catalog item params
func (o *RepublishCatalogItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the republish catalog item params
func (o *RepublishCatalogItemParams) WithContext(ctx context.Context) *RepublishCatalogItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the republish catalog item params
func (o *RepublishCatalogItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the republish catalog item params
func (o *RepublishCatalogItemParams) WithHTTPClient(client *http.Client) *RepublishCatalogItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the republish catalog item params
func (o *RepublishCatalogItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogItemID adds the catalogItemID to the republish catalog item params
func (o *RepublishCatalogItemParams) WithCatalogItemID(catalogItemID strfmt.UUID) *RepublishCatalogItemParams {
	o.SetCatalogItemID(catalogItemID)
	return o
}

// SetCatalogItemID adds the catalogItemId to the republish catalog item params
func (o *RepublishCatalogItemParams) SetCatalogItemID(catalogItemID strfmt.UUID) {
	o.CatalogItemID = catalogItemID
}

// WithRequest adds the request to the republish catalog item params
func (o *RepublishCatalogItemParams) WithRequest(request *models.CatalogItemPublishRequest) *RepublishCatalogItemParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the republish catalog item params
func (o *RepublishCatalogItemParams) SetRequest(request *models.CatalogItemPublishRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *RepublishCatalogItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param catalogItemId
	if err := r.SetPathParam("catalogItemId", o.CatalogItemID.String()); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
