// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewCloneByNameUsingPOSTParams creates a new CloneByNameUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCloneByNameUsingPOSTParams() *CloneByNameUsingPOSTParams {
	return &CloneByNameUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCloneByNameUsingPOSTParamsWithTimeout creates a new CloneByNameUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewCloneByNameUsingPOSTParamsWithTimeout(timeout time.Duration) *CloneByNameUsingPOSTParams {
	return &CloneByNameUsingPOSTParams{
		timeout: timeout,
	}
}

// NewCloneByNameUsingPOSTParamsWithContext creates a new CloneByNameUsingPOSTParams object
// with the ability to set a context for a request.
func NewCloneByNameUsingPOSTParamsWithContext(ctx context.Context) *CloneByNameUsingPOSTParams {
	return &CloneByNameUsingPOSTParams{
		Context: ctx,
	}
}

// NewCloneByNameUsingPOSTParamsWithHTTPClient creates a new CloneByNameUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewCloneByNameUsingPOSTParamsWithHTTPClient(client *http.Client) *CloneByNameUsingPOSTParams {
	return &CloneByNameUsingPOSTParams{
		HTTPClient: client,
	}
}

/* CloneByNameUsingPOSTParams contains all the parameters to send to the API endpoint
   for the clone by name using p o s t operation.

   Typically these are written to a http.Request.
*/
type CloneByNameUsingPOSTParams struct {

	/* Authorization.

	   Bearer token
	*/
	Authorization string

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /codestream/api/about
	*/
	APIVersion string

	/* Body.

	   Request object for actions such as cloning
	*/
	Body models.ServiceRequest

	/* Name.

	   The name of the Gerrit Listener
	*/
	Name string

	/* Project.

	   The project the Gerrit Listener belongs to
	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the clone by name using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloneByNameUsingPOSTParams) WithDefaults() *CloneByNameUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the clone by name using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloneByNameUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithTimeout(timeout time.Duration) *CloneByNameUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithContext(ctx context.Context) *CloneByNameUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithHTTPClient(client *http.Client) *CloneByNameUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithAuthorization(authorization string) *CloneByNameUsingPOSTParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAPIVersion adds the aPIVersion to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithAPIVersion(aPIVersion string) *CloneByNameUsingPOSTParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithBody(body models.ServiceRequest) *CloneByNameUsingPOSTParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetBody(body models.ServiceRequest) {
	o.Body = body
}

// WithName adds the name to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithName(name string) *CloneByNameUsingPOSTParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetName(name string) {
	o.Name = name
}

// WithProject adds the project to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) WithProject(project string) *CloneByNameUsingPOSTParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the clone by name using p o s t params
func (o *CloneByNameUsingPOSTParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *CloneByNameUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param apiVersion
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion

	if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
