// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware/vra-sdk-go/pkg/models"
)

// DeleteUsingDELETE7Reader is a Reader for the DeleteUsingDELETE7 structure.
type DeleteUsingDELETE7Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsingDELETE7Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUsingDELETE7OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteUsingDELETE7Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteUsingDELETE7Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteUsingDELETE7NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteUsingDELETE7InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteUsingDELETE7OK creates a DeleteUsingDELETE7OK with default headers values
func NewDeleteUsingDELETE7OK() *DeleteUsingDELETE7OK {
	return &DeleteUsingDELETE7OK{}
}

/*DeleteUsingDELETE7OK handles this case with default header values.

'Success' with Git Webhook Delete
*/
type DeleteUsingDELETE7OK struct {
	Payload models.GitWebhook
}

func (o *DeleteUsingDELETE7OK) Error() string {
	return fmt.Sprintf("[DELETE /codestream/api/git-webhooks/{id}][%d] deleteUsingDELETE7OK  %+v", 200, o.Payload)
}

func (o *DeleteUsingDELETE7OK) GetPayload() models.GitWebhook {
	return o.Payload
}

func (o *DeleteUsingDELETE7OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload as interface type
	payload, err := models.UnmarshalGitWebhook(response.Body(), consumer)
	if err != nil {
		return err
	}
	o.Payload = payload

	return nil
}

// NewDeleteUsingDELETE7Unauthorized creates a DeleteUsingDELETE7Unauthorized with default headers values
func NewDeleteUsingDELETE7Unauthorized() *DeleteUsingDELETE7Unauthorized {
	return &DeleteUsingDELETE7Unauthorized{}
}

/*DeleteUsingDELETE7Unauthorized handles this case with default header values.

Unauthorized Request
*/
type DeleteUsingDELETE7Unauthorized struct {
}

func (o *DeleteUsingDELETE7Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /codestream/api/git-webhooks/{id}][%d] deleteUsingDELETE7Unauthorized ", 401)
}

func (o *DeleteUsingDELETE7Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUsingDELETE7Forbidden creates a DeleteUsingDELETE7Forbidden with default headers values
func NewDeleteUsingDELETE7Forbidden() *DeleteUsingDELETE7Forbidden {
	return &DeleteUsingDELETE7Forbidden{}
}

/*DeleteUsingDELETE7Forbidden handles this case with default header values.

Forbidden
*/
type DeleteUsingDELETE7Forbidden struct {
}

func (o *DeleteUsingDELETE7Forbidden) Error() string {
	return fmt.Sprintf("[DELETE /codestream/api/git-webhooks/{id}][%d] deleteUsingDELETE7Forbidden ", 403)
}

func (o *DeleteUsingDELETE7Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUsingDELETE7NotFound creates a DeleteUsingDELETE7NotFound with default headers values
func NewDeleteUsingDELETE7NotFound() *DeleteUsingDELETE7NotFound {
	return &DeleteUsingDELETE7NotFound{}
}

/*DeleteUsingDELETE7NotFound handles this case with default header values.

Not Found
*/
type DeleteUsingDELETE7NotFound struct {
}

func (o *DeleteUsingDELETE7NotFound) Error() string {
	return fmt.Sprintf("[DELETE /codestream/api/git-webhooks/{id}][%d] deleteUsingDELETE7NotFound ", 404)
}

func (o *DeleteUsingDELETE7NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUsingDELETE7InternalServerError creates a DeleteUsingDELETE7InternalServerError with default headers values
func NewDeleteUsingDELETE7InternalServerError() *DeleteUsingDELETE7InternalServerError {
	return &DeleteUsingDELETE7InternalServerError{}
}

/*DeleteUsingDELETE7InternalServerError handles this case with default header values.

Server Error
*/
type DeleteUsingDELETE7InternalServerError struct {
}

func (o *DeleteUsingDELETE7InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /codestream/api/git-webhooks/{id}][%d] deleteUsingDELETE7InternalServerError ", 500)
}

func (o *DeleteUsingDELETE7InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
