// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllGitEventsUsingGETParams creates a new GetAllGitEventsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllGitEventsUsingGETParams() *GetAllGitEventsUsingGETParams {
	return &GetAllGitEventsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllGitEventsUsingGETParamsWithTimeout creates a new GetAllGitEventsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetAllGitEventsUsingGETParamsWithTimeout(timeout time.Duration) *GetAllGitEventsUsingGETParams {
	return &GetAllGitEventsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetAllGitEventsUsingGETParamsWithContext creates a new GetAllGitEventsUsingGETParams object
// with the ability to set a context for a request.
func NewGetAllGitEventsUsingGETParamsWithContext(ctx context.Context) *GetAllGitEventsUsingGETParams {
	return &GetAllGitEventsUsingGETParams{
		Context: ctx,
	}
}

// NewGetAllGitEventsUsingGETParamsWithHTTPClient creates a new GetAllGitEventsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllGitEventsUsingGETParamsWithHTTPClient(client *http.Client) *GetAllGitEventsUsingGETParams {
	return &GetAllGitEventsUsingGETParams{
		HTTPClient: client,
	}
}

/*
GetAllGitEventsUsingGETParams contains all the parameters to send to the API endpoint

	for the get all git events using g e t operation.

	Typically these are written to a http.Request.
*/
type GetAllGitEventsUsingGETParams struct {

	/* DollarFilter.

	   To list Git Events with OData like filter
	*/
	DollarFilter *string

	/* DollarOrderby.

	   Order by attribute

	   Default: "name desc"
	*/
	DollarOrderby *string

	/* DollarSkip.

	   To skip 'n' Git Events for listing

	   Default: "0"
	*/
	DollarSkip *string

	/* DollarTop.

	   To list top 'n' Git Events for listing

	   Default: "25"
	*/
	DollarTop *string

	/* Authorization.

	   Bearer token
	*/
	Authorization string

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /codestream/api/about
	*/
	APIVersion string

	/* Page.

	   To select 'n'th page for listing

	   Default: "0"
	*/
	Page *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all git events using get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllGitEventsUsingGETParams) WithDefaults() *GetAllGitEventsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all git events using get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllGitEventsUsingGETParams) SetDefaults() {
	var (
		dollarOrderbyDefault = string("name desc")

		dollarSkipDefault = string("0")

		dollarTopDefault = string("25")

		pageDefault = string("0")
	)

	val := GetAllGitEventsUsingGETParams{
		DollarOrderby: &dollarOrderbyDefault,
		DollarSkip:    &dollarSkipDefault,
		DollarTop:     &dollarTopDefault,
		Page:          &pageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithTimeout(timeout time.Duration) *GetAllGitEventsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithContext(ctx context.Context) *GetAllGitEventsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithHTTPClient(client *http.Client) *GetAllGitEventsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithDollarFilter(dollarFilter *string) *GetAllGitEventsUsingGETParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarOrderby adds the dollarOrderby to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithDollarOrderby(dollarOrderby *string) *GetAllGitEventsUsingGETParams {
	o.SetDollarOrderby(dollarOrderby)
	return o
}

// SetDollarOrderby adds the dollarOrderby to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetDollarOrderby(dollarOrderby *string) {
	o.DollarOrderby = dollarOrderby
}

// WithDollarSkip adds the dollarSkip to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithDollarSkip(dollarSkip *string) *GetAllGitEventsUsingGETParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetDollarSkip(dollarSkip *string) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithDollarTop(dollarTop *string) *GetAllGitEventsUsingGETParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetDollarTop(dollarTop *string) {
	o.DollarTop = dollarTop
}

// WithAuthorization adds the authorization to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithAuthorization(authorization string) *GetAllGitEventsUsingGETParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAPIVersion adds the aPIVersion to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithAPIVersion(aPIVersion string) *GetAllGitEventsUsingGETParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithPage adds the page to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) WithPage(page *string) *GetAllGitEventsUsingGETParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get all git events using get params
func (o *GetAllGitEventsUsingGETParams) SetPage(page *string) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllGitEventsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	if o.DollarOrderby != nil {

		// query param $orderby
		var qrDollarOrderby string

		if o.DollarOrderby != nil {
			qrDollarOrderby = *o.DollarOrderby
		}
		qDollarOrderby := qrDollarOrderby
		if qDollarOrderby != "" {

			if err := r.SetQueryParam("$orderby", qDollarOrderby); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip string

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := qrDollarSkip
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop string

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := qrDollarTop
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param apiVersion
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion

	if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage string

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := qrPage
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
