// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewPatchByNameUsingPATCHParams creates a new PatchByNameUsingPATCHParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchByNameUsingPATCHParams() *PatchByNameUsingPATCHParams {
	return &PatchByNameUsingPATCHParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchByNameUsingPATCHParamsWithTimeout creates a new PatchByNameUsingPATCHParams object
// with the ability to set a timeout on a request.
func NewPatchByNameUsingPATCHParamsWithTimeout(timeout time.Duration) *PatchByNameUsingPATCHParams {
	return &PatchByNameUsingPATCHParams{
		timeout: timeout,
	}
}

// NewPatchByNameUsingPATCHParamsWithContext creates a new PatchByNameUsingPATCHParams object
// with the ability to set a context for a request.
func NewPatchByNameUsingPATCHParamsWithContext(ctx context.Context) *PatchByNameUsingPATCHParams {
	return &PatchByNameUsingPATCHParams{
		Context: ctx,
	}
}

// NewPatchByNameUsingPATCHParamsWithHTTPClient creates a new PatchByNameUsingPATCHParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchByNameUsingPATCHParamsWithHTTPClient(client *http.Client) *PatchByNameUsingPATCHParams {
	return &PatchByNameUsingPATCHParams{
		HTTPClient: client,
	}
}

/* PatchByNameUsingPATCHParams contains all the parameters to send to the API endpoint
   for the patch by name using p a t c h operation.

   Typically these are written to a http.Request.
*/
type PatchByNameUsingPATCHParams struct {

	/* Authorization.

	   Bearer token
	*/
	Authorization string

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /codestream/api/about
	*/
	APIVersion string

	/* DockerRegistryWebhookPatch.

	   dockerRegistryWebhookPatch
	*/
	DockerRegistryWebhookPatch models.DockerRegistryWebhookPatch

	/* Name.

	   name
	*/
	Name string

	/* Project.

	   project
	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch by name using p a t c h params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchByNameUsingPATCHParams) WithDefaults() *PatchByNameUsingPATCHParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch by name using p a t c h params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchByNameUsingPATCHParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithTimeout(timeout time.Duration) *PatchByNameUsingPATCHParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithContext(ctx context.Context) *PatchByNameUsingPATCHParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithHTTPClient(client *http.Client) *PatchByNameUsingPATCHParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithAuthorization(authorization string) *PatchByNameUsingPATCHParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAPIVersion adds the aPIVersion to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithAPIVersion(aPIVersion string) *PatchByNameUsingPATCHParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithDockerRegistryWebhookPatch adds the dockerRegistryWebhookPatch to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithDockerRegistryWebhookPatch(dockerRegistryWebhookPatch models.DockerRegistryWebhookPatch) *PatchByNameUsingPATCHParams {
	o.SetDockerRegistryWebhookPatch(dockerRegistryWebhookPatch)
	return o
}

// SetDockerRegistryWebhookPatch adds the dockerRegistryWebhookPatch to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetDockerRegistryWebhookPatch(dockerRegistryWebhookPatch models.DockerRegistryWebhookPatch) {
	o.DockerRegistryWebhookPatch = dockerRegistryWebhookPatch
}

// WithName adds the name to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithName(name string) *PatchByNameUsingPATCHParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetName(name string) {
	o.Name = name
}

// WithProject adds the project to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) WithProject(project string) *PatchByNameUsingPATCHParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the patch by name using p a t c h params
func (o *PatchByNameUsingPATCHParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *PatchByNameUsingPATCHParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param apiVersion
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion

	if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.DockerRegistryWebhookPatch); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
