// Code generated by go-swagger; DO NOT EDIT.

package triggers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewValidateGerritListenerUsingPOSTParams creates a new ValidateGerritListenerUsingPOSTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateGerritListenerUsingPOSTParams() *ValidateGerritListenerUsingPOSTParams {
	return &ValidateGerritListenerUsingPOSTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateGerritListenerUsingPOSTParamsWithTimeout creates a new ValidateGerritListenerUsingPOSTParams object
// with the ability to set a timeout on a request.
func NewValidateGerritListenerUsingPOSTParamsWithTimeout(timeout time.Duration) *ValidateGerritListenerUsingPOSTParams {
	return &ValidateGerritListenerUsingPOSTParams{
		timeout: timeout,
	}
}

// NewValidateGerritListenerUsingPOSTParamsWithContext creates a new ValidateGerritListenerUsingPOSTParams object
// with the ability to set a context for a request.
func NewValidateGerritListenerUsingPOSTParamsWithContext(ctx context.Context) *ValidateGerritListenerUsingPOSTParams {
	return &ValidateGerritListenerUsingPOSTParams{
		Context: ctx,
	}
}

// NewValidateGerritListenerUsingPOSTParamsWithHTTPClient creates a new ValidateGerritListenerUsingPOSTParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateGerritListenerUsingPOSTParamsWithHTTPClient(client *http.Client) *ValidateGerritListenerUsingPOSTParams {
	return &ValidateGerritListenerUsingPOSTParams{
		HTTPClient: client,
	}
}

/*
ValidateGerritListenerUsingPOSTParams contains all the parameters to send to the API endpoint

	for the validate gerrit listener using p o s t operation.

	Typically these are written to a http.Request.
*/
type ValidateGerritListenerUsingPOSTParams struct {

	/* Authorization.

	   Bearer token
	*/
	Authorization string

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /codestream/api/about
	*/
	APIVersion string

	/* GerritListenerspec.

	   gerritListenerspec
	*/
	GerritListenerspec models.GerritListenerSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate gerrit listener using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateGerritListenerUsingPOSTParams) WithDefaults() *ValidateGerritListenerUsingPOSTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate gerrit listener using p o s t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateGerritListenerUsingPOSTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithTimeout(timeout time.Duration) *ValidateGerritListenerUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithContext(ctx context.Context) *ValidateGerritListenerUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithHTTPClient(client *http.Client) *ValidateGerritListenerUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithAuthorization(authorization string) *ValidateGerritListenerUsingPOSTParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAPIVersion adds the aPIVersion to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithAPIVersion(aPIVersion string) *ValidateGerritListenerUsingPOSTParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithGerritListenerspec adds the gerritListenerspec to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) WithGerritListenerspec(gerritListenerspec models.GerritListenerSpec) *ValidateGerritListenerUsingPOSTParams {
	o.SetGerritListenerspec(gerritListenerspec)
	return o
}

// SetGerritListenerspec adds the gerritListenerspec to the validate gerrit listener using p o s t params
func (o *ValidateGerritListenerUsingPOSTParams) SetGerritListenerspec(gerritListenerspec models.GerritListenerSpec) {
	o.GerritListenerspec = gerritListenerspec
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateGerritListenerUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// query param apiVersion
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion

	if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.GerritListenerspec); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
