// Code generated by go-swagger; DO NOT EDIT.

package onboarding_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryResourcesParams creates a new QueryResourcesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryResourcesParams() *QueryResourcesParams {
	return &QueryResourcesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryResourcesParamsWithTimeout creates a new QueryResourcesParams object
// with the ability to set a timeout on a request.
func NewQueryResourcesParamsWithTimeout(timeout time.Duration) *QueryResourcesParams {
	return &QueryResourcesParams{
		timeout: timeout,
	}
}

// NewQueryResourcesParamsWithContext creates a new QueryResourcesParams object
// with the ability to set a context for a request.
func NewQueryResourcesParamsWithContext(ctx context.Context) *QueryResourcesParams {
	return &QueryResourcesParams{
		Context: ctx,
	}
}

// NewQueryResourcesParamsWithHTTPClient creates a new QueryResourcesParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryResourcesParamsWithHTTPClient(client *http.Client) *QueryResourcesParams {
	return &QueryResourcesParams{
		HTTPClient: client,
	}
}

/*
QueryResourcesParams contains all the parameters to send to the API endpoint

	for the query resources operation.

	Typically these are written to a http.Request.
*/
type QueryResourcesParams struct {

	/* DollarExpand.

	   Expand document contents
	*/
	DollarExpand *bool

	/* DollarFilter.

	   OData filter expression
	*/
	DollarFilter *string

	/* DollarLimit.

	   Set maximum number of documents to return in this query
	*/
	DollarLimit *int64

	/* DollarSelect.

	   Comma-separated list of fields to populate in query result
	*/
	DollarSelect *string

	/* DollarTenantLinks.

	   Comma-separated list
	*/
	DollarTenantLinks *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query resources params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryResourcesParams) WithDefaults() *QueryResourcesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query resources params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryResourcesParams) SetDefaults() {
	var (
		dollarExpandDefault = bool(false)
	)

	val := QueryResourcesParams{
		DollarExpand: &dollarExpandDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the query resources params
func (o *QueryResourcesParams) WithTimeout(timeout time.Duration) *QueryResourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query resources params
func (o *QueryResourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query resources params
func (o *QueryResourcesParams) WithContext(ctx context.Context) *QueryResourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query resources params
func (o *QueryResourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query resources params
func (o *QueryResourcesParams) WithHTTPClient(client *http.Client) *QueryResourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query resources params
func (o *QueryResourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarExpand adds the dollarExpand to the query resources params
func (o *QueryResourcesParams) WithDollarExpand(dollarExpand *bool) *QueryResourcesParams {
	o.SetDollarExpand(dollarExpand)
	return o
}

// SetDollarExpand adds the dollarExpand to the query resources params
func (o *QueryResourcesParams) SetDollarExpand(dollarExpand *bool) {
	o.DollarExpand = dollarExpand
}

// WithDollarFilter adds the dollarFilter to the query resources params
func (o *QueryResourcesParams) WithDollarFilter(dollarFilter *string) *QueryResourcesParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the query resources params
func (o *QueryResourcesParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarLimit adds the dollarLimit to the query resources params
func (o *QueryResourcesParams) WithDollarLimit(dollarLimit *int64) *QueryResourcesParams {
	o.SetDollarLimit(dollarLimit)
	return o
}

// SetDollarLimit adds the dollarLimit to the query resources params
func (o *QueryResourcesParams) SetDollarLimit(dollarLimit *int64) {
	o.DollarLimit = dollarLimit
}

// WithDollarSelect adds the dollarSelect to the query resources params
func (o *QueryResourcesParams) WithDollarSelect(dollarSelect *string) *QueryResourcesParams {
	o.SetDollarSelect(dollarSelect)
	return o
}

// SetDollarSelect adds the dollarSelect to the query resources params
func (o *QueryResourcesParams) SetDollarSelect(dollarSelect *string) {
	o.DollarSelect = dollarSelect
}

// WithDollarTenantLinks adds the dollarTenantLinks to the query resources params
func (o *QueryResourcesParams) WithDollarTenantLinks(dollarTenantLinks *string) *QueryResourcesParams {
	o.SetDollarTenantLinks(dollarTenantLinks)
	return o
}

// SetDollarTenantLinks adds the dollarTenantLinks to the query resources params
func (o *QueryResourcesParams) SetDollarTenantLinks(dollarTenantLinks *string) {
	o.DollarTenantLinks = dollarTenantLinks
}

// WriteToRequest writes these params to a swagger request
func (o *QueryResourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarExpand != nil {

		// query param $expand
		var qrDollarExpand bool

		if o.DollarExpand != nil {
			qrDollarExpand = *o.DollarExpand
		}
		qDollarExpand := swag.FormatBool(qrDollarExpand)
		if qDollarExpand != "" {

			if err := r.SetQueryParam("$expand", qDollarExpand); err != nil {
				return err
			}
		}
	}

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	if o.DollarLimit != nil {

		// query param $limit
		var qrDollarLimit int64

		if o.DollarLimit != nil {
			qrDollarLimit = *o.DollarLimit
		}
		qDollarLimit := swag.FormatInt64(qrDollarLimit)
		if qDollarLimit != "" {

			if err := r.SetQueryParam("$limit", qDollarLimit); err != nil {
				return err
			}
		}
	}

	if o.DollarSelect != nil {

		// query param $select
		var qrDollarSelect string

		if o.DollarSelect != nil {
			qrDollarSelect = *o.DollarSelect
		}
		qDollarSelect := qrDollarSelect
		if qDollarSelect != "" {

			if err := r.SetQueryParam("$select", qDollarSelect); err != nil {
				return err
			}
		}
	}

	if o.DollarTenantLinks != nil {

		// query param $tenantLinks
		var qrDollarTenantLinks string

		if o.DollarTenantLinks != nil {
			qrDollarTenantLinks = *o.DollarTenantLinks
		}
		qDollarTenantLinks := qrDollarTenantLinks
		if qDollarTenantLinks != "" {

			if err := r.SetQueryParam("$tenantLinks", qDollarTenantLinks); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
