// Code generated by go-swagger; DO NOT EDIT.

package cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// CreateCloudAccountAsyncReader is a Reader for the CreateCloudAccountAsync structure.
type CreateCloudAccountAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCloudAccountAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewCreateCloudAccountAsyncAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCloudAccountAsyncBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCloudAccountAsyncForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCloudAccountAsyncAccepted creates a CreateCloudAccountAsyncAccepted with default headers values
func NewCreateCloudAccountAsyncAccepted() *CreateCloudAccountAsyncAccepted {
	return &CreateCloudAccountAsyncAccepted{}
}

/*
CreateCloudAccountAsyncAccepted describes a response with status code 202, with default header values.

successful operation
*/
type CreateCloudAccountAsyncAccepted struct {
	Payload *models.RequestTracker
}

// IsSuccess returns true when this create cloud account async accepted response has a 2xx status code
func (o *CreateCloudAccountAsyncAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create cloud account async accepted response has a 3xx status code
func (o *CreateCloudAccountAsyncAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cloud account async accepted response has a 4xx status code
func (o *CreateCloudAccountAsyncAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cloud account async accepted response has a 5xx status code
func (o *CreateCloudAccountAsyncAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this create cloud account async accepted response a status code equal to that given
func (o *CreateCloudAccountAsyncAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *CreateCloudAccountAsyncAccepted) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncAccepted  %+v", 202, o.Payload)
}

func (o *CreateCloudAccountAsyncAccepted) String() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncAccepted  %+v", 202, o.Payload)
}

func (o *CreateCloudAccountAsyncAccepted) GetPayload() *models.RequestTracker {
	return o.Payload
}

func (o *CreateCloudAccountAsyncAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestTracker)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCloudAccountAsyncBadRequest creates a CreateCloudAccountAsyncBadRequest with default headers values
func NewCreateCloudAccountAsyncBadRequest() *CreateCloudAccountAsyncBadRequest {
	return &CreateCloudAccountAsyncBadRequest{}
}

/*
CreateCloudAccountAsyncBadRequest describes a response with status code 400, with default header values.

Invalid Request - bad data
*/
type CreateCloudAccountAsyncBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cloud account async bad request response has a 2xx status code
func (o *CreateCloudAccountAsyncBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cloud account async bad request response has a 3xx status code
func (o *CreateCloudAccountAsyncBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cloud account async bad request response has a 4xx status code
func (o *CreateCloudAccountAsyncBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cloud account async bad request response has a 5xx status code
func (o *CreateCloudAccountAsyncBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create cloud account async bad request response a status code equal to that given
func (o *CreateCloudAccountAsyncBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateCloudAccountAsyncBadRequest) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCloudAccountAsyncBadRequest) String() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncBadRequest  %+v", 400, o.Payload)
}

func (o *CreateCloudAccountAsyncBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateCloudAccountAsyncBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCloudAccountAsyncForbidden creates a CreateCloudAccountAsyncForbidden with default headers values
func NewCreateCloudAccountAsyncForbidden() *CreateCloudAccountAsyncForbidden {
	return &CreateCloudAccountAsyncForbidden{}
}

/*
CreateCloudAccountAsyncForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateCloudAccountAsyncForbidden struct {
	Payload *models.ServiceErrorResponse
}

// IsSuccess returns true when this create cloud account async forbidden response has a 2xx status code
func (o *CreateCloudAccountAsyncForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cloud account async forbidden response has a 3xx status code
func (o *CreateCloudAccountAsyncForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cloud account async forbidden response has a 4xx status code
func (o *CreateCloudAccountAsyncForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cloud account async forbidden response has a 5xx status code
func (o *CreateCloudAccountAsyncForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create cloud account async forbidden response a status code equal to that given
func (o *CreateCloudAccountAsyncForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CreateCloudAccountAsyncForbidden) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncForbidden  %+v", 403, o.Payload)
}

func (o *CreateCloudAccountAsyncForbidden) String() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts][%d] createCloudAccountAsyncForbidden  %+v", 403, o.Payload)
}

func (o *CreateCloudAccountAsyncForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *CreateCloudAccountAsyncForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
