// Code generated by go-swagger; DO NOT EDIT.

package cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// EnumerateVcfRegionsReader is a Reader for the EnumerateVcfRegions structure.
type EnumerateVcfRegionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnumerateVcfRegionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEnumerateVcfRegionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEnumerateVcfRegionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEnumerateVcfRegionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEnumerateVcfRegionsOK creates a EnumerateVcfRegionsOK with default headers values
func NewEnumerateVcfRegionsOK() *EnumerateVcfRegionsOK {
	return &EnumerateVcfRegionsOK{}
}

/* EnumerateVcfRegionsOK describes a response with status code 200, with default header values.

successful operation
*/
type EnumerateVcfRegionsOK struct {
	Payload *models.CloudAccountRegions
}

func (o *EnumerateVcfRegionsOK) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts-vcf/region-enumeration][%d] enumerateVcfRegionsOK  %+v", 200, o.Payload)
}
func (o *EnumerateVcfRegionsOK) GetPayload() *models.CloudAccountRegions {
	return o.Payload
}

func (o *EnumerateVcfRegionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudAccountRegions)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnumerateVcfRegionsBadRequest creates a EnumerateVcfRegionsBadRequest with default headers values
func NewEnumerateVcfRegionsBadRequest() *EnumerateVcfRegionsBadRequest {
	return &EnumerateVcfRegionsBadRequest{}
}

/* EnumerateVcfRegionsBadRequest describes a response with status code 400, with default header values.

Invalid Request - bad data
*/
type EnumerateVcfRegionsBadRequest struct {
	Payload *models.Error
}

func (o *EnumerateVcfRegionsBadRequest) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts-vcf/region-enumeration][%d] enumerateVcfRegionsBadRequest  %+v", 400, o.Payload)
}
func (o *EnumerateVcfRegionsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *EnumerateVcfRegionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnumerateVcfRegionsForbidden creates a EnumerateVcfRegionsForbidden with default headers values
func NewEnumerateVcfRegionsForbidden() *EnumerateVcfRegionsForbidden {
	return &EnumerateVcfRegionsForbidden{}
}

/* EnumerateVcfRegionsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type EnumerateVcfRegionsForbidden struct {
	Payload *models.ServiceErrorResponse
}

func (o *EnumerateVcfRegionsForbidden) Error() string {
	return fmt.Sprintf("[POST /iaas/api/cloud-accounts-vcf/region-enumeration][%d] enumerateVcfRegionsForbidden  %+v", 403, o.Payload)
}
func (o *EnumerateVcfRegionsForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *EnumerateVcfRegionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
