// Code generated by go-swagger; DO NOT EDIT.

package cloud_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewUpdateNsxVCloudAccountAsyncParams creates a new UpdateNsxVCloudAccountAsyncParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateNsxVCloudAccountAsyncParams() *UpdateNsxVCloudAccountAsyncParams {
	return &UpdateNsxVCloudAccountAsyncParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNsxVCloudAccountAsyncParamsWithTimeout creates a new UpdateNsxVCloudAccountAsyncParams object
// with the ability to set a timeout on a request.
func NewUpdateNsxVCloudAccountAsyncParamsWithTimeout(timeout time.Duration) *UpdateNsxVCloudAccountAsyncParams {
	return &UpdateNsxVCloudAccountAsyncParams{
		timeout: timeout,
	}
}

// NewUpdateNsxVCloudAccountAsyncParamsWithContext creates a new UpdateNsxVCloudAccountAsyncParams object
// with the ability to set a context for a request.
func NewUpdateNsxVCloudAccountAsyncParamsWithContext(ctx context.Context) *UpdateNsxVCloudAccountAsyncParams {
	return &UpdateNsxVCloudAccountAsyncParams{
		Context: ctx,
	}
}

// NewUpdateNsxVCloudAccountAsyncParamsWithHTTPClient creates a new UpdateNsxVCloudAccountAsyncParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateNsxVCloudAccountAsyncParamsWithHTTPClient(client *http.Client) *UpdateNsxVCloudAccountAsyncParams {
	return &UpdateNsxVCloudAccountAsyncParams{
		HTTPClient: client,
	}
}

/*
UpdateNsxVCloudAccountAsyncParams contains all the parameters to send to the API endpoint

	for the update nsx v cloud account async operation.

	Typically these are written to a http.Request.
*/
type UpdateNsxVCloudAccountAsyncParams struct {

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information refer to /iaas/api/about
	*/
	APIVersion *string

	/* Body.

	   NSX-V cloud account details to be updated
	*/
	Body *models.UpdateCloudAccountNsxVSpecification

	/* ID.

	   Cloud account id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update nsx v cloud account async params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNsxVCloudAccountAsyncParams) WithDefaults() *UpdateNsxVCloudAccountAsyncParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update nsx v cloud account async params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateNsxVCloudAccountAsyncParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithTimeout(timeout time.Duration) *UpdateNsxVCloudAccountAsyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithContext(ctx context.Context) *UpdateNsxVCloudAccountAsyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithHTTPClient(client *http.Client) *UpdateNsxVCloudAccountAsyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithAPIVersion(aPIVersion *string) *UpdateNsxVCloudAccountAsyncParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithBody(body *models.UpdateCloudAccountNsxVSpecification) *UpdateNsxVCloudAccountAsyncParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetBody(body *models.UpdateCloudAccountNsxVSpecification) {
	o.Body = body
}

// WithID adds the id to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) WithID(id string) *UpdateNsxVCloudAccountAsyncParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update nsx v cloud account async params
func (o *UpdateNsxVCloudAccountAsyncParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNsxVCloudAccountAsyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
