#!/usr/bin/env python3

import json


# This is the location of the IaaS swagger
filename = "swagger/cas-iaas.json"

# The $filter parameter to insert
filter_spec = {
    "name": "$filter",
    "in": "query",
    "description": "Add a filter to return limited results",
    "required": False,
    "type": "string"
}

# List of paths to insert $filter
paths = [
    "/iaas/api/fabric-images",
    "/iaas/api/fabric-networks",
    "/iaas/api/network-domains",
    "/iaas/api/security-groups",
    "/iaas/api/projects",
]


if __name__ == "__main__":
    # read in the swagger spec
    swagger = json.loads(open(filename).read())

    # Update the needed paths
    for p in paths:
        param_list = swagger['paths'][p]['get']['parameters']
        param_name_list = [d['name'] for d in param_list]
        if filter_spec['name'] not in param_name_list:
            param_list.insert(0, filter_spec)

    # Overwrite the swagger spec
    f = open(filename, "w")
    f.write(json.dumps(swagger, sort_keys=False, indent=4))
    f.write('\n')
