#!/usr/bin/env python3

import argparse
import json


# This is the location of the IaaS swagger
filename = "swagger/vra-combined.json"


def add_filter_params(swagger):
    # The $filter parameter to insert
    filter_spec = {
        "name": "$filter",
        "in": "query",
        "description": "Add a filter to return limited results",
        "required": False,
        "type": "string"
    }

    # List of paths to insert $filter
    paths = [
        "/iaas/api/fabric-images",
        "/iaas/api/fabric-networks",
        "/iaas/api/network-domains",
        "/iaas/api/projects",
        "/iaas/api/security-groups",
        "/iaas/api/network-profiles",
        "/iaas/api/storage-profiles",
        "/iaas/api/block-devices",
        "/iaas/api/machines",
    ]

    # Update the needed paths
    for p in paths:
        param_list = swagger['paths'][p]['get']['parameters']
        param_name_list = [d['name'] for d in param_list]
        if filter_spec['name'] not in param_name_list:
            param_list.insert(0, filter_spec)


def add_204(swagger):
    paths = [
        ('/iaas/api/block-devices/{id}', 'delete'),
        ('/iaas/api/machines/{id}/disks/{id1}', 'delete'),
    ]

    # Update the needed paths
    for p, op in paths:
        responses = swagger['paths'][p][op]['responses']
        if '204' not in responses:
            responses['204'] = {"description": "No Content"}


def change_response_model_to_request_tracker(swagger):
    # List of paths, operations, and status code to update the response model
    paths = [
        ('/iaas/api/machines/{id}/disks', 'post', '200'),
        ('/iaas/api/machines/{id}/disks/{id1}', 'delete', '202'),
    ]

    # Update the needed paths
    for (p, op, response_code) in paths:
        schema = swagger['paths'][p][op]['responses'][response_code]['schema']
        schema['$ref'] = '#/definitions/RequestTracker'


def add_global_security(swagger):
    security_def = {
        "Bearer": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
        }
    }

    if 'securityDefinitions' not in swagger:
        swagger['securityDefinitions'] = security_def


def add_security(swagger):
    exclude_paths = [
        '/iaas/api/about',
        '/iaas/api/login',
        '/blueprint/api/about'
    ]
    bearer_security = [
        {"Bearer": []},
    ]

    # Update the needed paths
    for p in swagger['paths']:
        if p in exclude_paths:
            continue
        param_list = swagger['paths'][p]
        for method in param_list:
            if 'security' not in swagger['paths'][p][method]:
                swagger['paths'][p][method]['security'] = bearer_security

def add_region_enumerate_return_code(swagger):
    path = '/iaas/api/cloud-accounts-vsphere/region-enumeration'
    responses = swagger['paths'][path]['post']['responses']
    responses['201'] = responses['200']


def add_network_ip_range_return_code(swagger):
    path = '"/iaas/api/network-ip-ranges'
    responses = swagger['paths'][path]['post']['responses']
    responses['201'] = responses['202']
    

def add_blockdevice_persistent(swagger):
    persistent = {
        "description": "Indicates whether the block device survives a delete action.",
        "type": "boolean",
        "example": True,
    }
    bd_props = swagger['definitions']['BlockDevice']['properties']
    if 'persistent' not in bd_props:
        bd_props['persistent'] = persistent

    bd_props = swagger['definitions']['BlockDeviceSpecification']['properties']
    if 'persistent' not in bd_props:
        bd_props['persistent'] = persistent


def add_blockdevice_delete_purge(swagger):
    bd = swagger['paths']['/iaas/api/block-devices/{id}']['delete']
    for p in bd['parameters']:
        if p['name'] == 'purge':
            return
    bd['parameters'].append({
        "in": "query",
        "name": "purge",
        "description": "Indicates if the disk has to be completely destroyed or should be kept in the system. Valid only for block devices with 'persistent' set to true.",
        "type": "boolean",
        "required": False
    })


def add_blockdevice_resize(swagger):
    bd = swagger['paths']['/iaas/api/block-devices/{id}']
    if 'post' in bd:
        return
    bd['post'] = {
        "summary": "Resize BlockDevice",
        "produces": [
            "application/json",
            "app/json"
        ],
        "description": "Resize operation on block device.",
        "operationId": "resizeBlockDevice",
        "responses": {
            "202": {
                "schema": {
                    "$ref": "#/definitions/RequestTracker"
                },
                "description": "successful operation"
            },
            "204": {
                "description": "No Content"
            },
            "403": {
                "description": "Forbidden"
            }
        },
        "parameters": [
            {
                "in": "path",
                "name": "id",
                "description": "The ID of the block device.",
                "type": "string",
                "required": True
            },
            {
                "in": "query",
                "name": "capacityInGB",
                "format": "int32",
                "description": "Resize Capacity in GB",
                "type": "integer",
                "required": True
            },
            {
                "in": "query",
                "name": "apiVersion",
                "description": "The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /iaas/api/about",
                "type": "string",
                "required": False
            }
        ],
        "tags": [
            "Disk"
        ]
    }


def add_404_not_found(swagger):
    # List of paths and operations to add a 404 not found
    paths = [
        ('/iaas/api/block-devices/{id}', 'get'),
    ]

    # Update the needed paths
    for (p, op) in paths:
        responses = swagger['paths'][p][op]['responses']
        if '404' not in responses:
            responses['404'] = {
                "description": "Not Found",
            }


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--omit-security', action='store_false')
    args = parser.parse_args()

    # read in the swagger spec
    swagger = json.loads(open(filename).read())

    add_filter_params(swagger)
    add_204(swagger)
    change_response_model_to_request_tracker(swagger)

    add_region_enumerate_return_code(swagger)

    add_blockdevice_persistent(swagger)
    add_blockdevice_delete_purge(swagger)
    add_blockdevice_resize(swagger)
    add_404_not_found(swagger)

    if args.omit_security:
        add_global_security(swagger)
        add_security(swagger)

    # Overwrite the swagger spec
    f = open(filename, "w")
    f.write(json.dumps(swagger, sort_keys=False, indent=2))
    f.write('\n')
