// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUsingDELETE8Params creates a new DeleteUsingDELETE8Params object
// with the default values initialized.
func NewDeleteUsingDELETE8Params() *DeleteUsingDELETE8Params {
	var ()
	return &DeleteUsingDELETE8Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUsingDELETE8ParamsWithTimeout creates a new DeleteUsingDELETE8Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUsingDELETE8ParamsWithTimeout(timeout time.Duration) *DeleteUsingDELETE8Params {
	var ()
	return &DeleteUsingDELETE8Params{

		timeout: timeout,
	}
}

// NewDeleteUsingDELETE8ParamsWithContext creates a new DeleteUsingDELETE8Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUsingDELETE8ParamsWithContext(ctx context.Context) *DeleteUsingDELETE8Params {
	var ()
	return &DeleteUsingDELETE8Params{

		Context: ctx,
	}
}

// NewDeleteUsingDELETE8ParamsWithHTTPClient creates a new DeleteUsingDELETE8Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUsingDELETE8ParamsWithHTTPClient(client *http.Client) *DeleteUsingDELETE8Params {
	var ()
	return &DeleteUsingDELETE8Params{
		HTTPClient: client,
	}
}

/*DeleteUsingDELETE8Params contains all the parameters to send to the API endpoint
for the delete using d e l e t e 8 operation typically these are written to a http.Request
*/
type DeleteUsingDELETE8Params struct {

	/*APIVersion
	  The version of the API in yyyy-MM-dd format (UTC). For versioning information please refer to /codestream/api/about

	*/
	APIVersion string
	/*ID
	  The ID of the Pipeline

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) WithTimeout(timeout time.Duration) *DeleteUsingDELETE8Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) WithContext(ctx context.Context) *DeleteUsingDELETE8Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) WithHTTPClient(client *http.Client) *DeleteUsingDELETE8Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) WithAPIVersion(aPIVersion string) *DeleteUsingDELETE8Params {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithID adds the id to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) WithID(id string) *DeleteUsingDELETE8Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete using d e l e t e 8 params
func (o *DeleteUsingDELETE8Params) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUsingDELETE8Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param apiVersion
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
