// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateResourceRequest create resource request
//
// swagger:model CreateResourceRequest
type CreateResourceRequest struct {

	// Link to the compute resource (machine) in the Provisioning service inventory.
	Link string `json:"link,omitempty"`

	// Resource name, usually the machine name. Will be propagated to Cloud Assembly.
	Name string `json:"name,omitempty"`

	// Tag links in the Provisioning service inventory associated with the machine.
	TagLinks []string `json:"tagLinks"`
}

// Validate validates this create resource request
func (m *CreateResourceRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create resource request based on context it is used
func (m *CreateResourceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateResourceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateResourceRequest) UnmarshalBinary(b []byte) error {
	var res CreateResourceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
