// Code generated by go-swagger; DO NOT EDIT.

package catalog_admin_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new catalog admin items API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog admin items API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetCatalogAdminItemsUsingGET returns a paginated list of catalog items
*/
func (a *Client) GetCatalogAdminItemsUsingGET(params *GetCatalogAdminItemsUsingGETParams) (*GetCatalogAdminItemsUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCatalogAdminItemsUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCatalogAdminItemsUsingGET",
		Method:             "GET",
		PathPattern:        "/catalog/api/admin/items",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCatalogAdminItemsUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetCatalogAdminItemsUsingGETOK), nil

}

/*
SetItemIconUsingPATCH sets an icon to a catalog item
*/
func (a *Client) SetItemIconUsingPATCH(params *SetItemIconUsingPATCHParams) (*SetItemIconUsingPATCHOK, *SetItemIconUsingPATCHNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSetItemIconUsingPATCHParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "setItemIconUsingPATCH",
		Method:             "PATCH",
		PathPattern:        "/catalog/api/admin/items/{id}",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SetItemIconUsingPATCHReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *SetItemIconUsingPATCHOK:
		return value, nil, nil
	case *SetItemIconUsingPATCHNoContent:
		return nil, value, nil
	}
	return nil, nil, nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
