// Code generated by go-swagger; DO NOT EDIT.

package catalog_admin_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCatalogItemsUsingGETParams creates a new GetCatalogItemsUsingGETParams object
// with the default values initialized.
func NewGetCatalogItemsUsingGETParams() *GetCatalogItemsUsingGETParams {
	var ()
	return &GetCatalogItemsUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogItemsUsingGETParamsWithTimeout creates a new GetCatalogItemsUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogItemsUsingGETParamsWithTimeout(timeout time.Duration) *GetCatalogItemsUsingGETParams {
	var ()
	return &GetCatalogItemsUsingGETParams{

		timeout: timeout,
	}
}

// NewGetCatalogItemsUsingGETParamsWithContext creates a new GetCatalogItemsUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogItemsUsingGETParamsWithContext(ctx context.Context) *GetCatalogItemsUsingGETParams {
	var ()
	return &GetCatalogItemsUsingGETParams{

		Context: ctx,
	}
}

// NewGetCatalogItemsUsingGETParamsWithHTTPClient creates a new GetCatalogItemsUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogItemsUsingGETParamsWithHTTPClient(client *http.Client) *GetCatalogItemsUsingGETParams {
	var ()
	return &GetCatalogItemsUsingGETParams{
		HTTPClient: client,
	}
}

/*GetCatalogItemsUsingGETParams contains all the parameters to send to the API endpoint
for the get catalog items using g e t operation typically these are written to a http.Request
*/
type GetCatalogItemsUsingGETParams struct {

	/*DollarOrderby
	  Sorting criteria in the format: property (asc|desc). Default sort order is ascending. Multiple sort criteria are supported.

	*/
	DollarOrderby []string
	/*DollarSkip
	  Number of records you want to skip

	*/
	DollarSkip *int32
	/*DollarTop
	  Number of records you want

	*/
	DollarTop *int32
	/*APIVersion
	  The version of the API in yyyy-MM-dd format (UTC). If you do not specify explicitly an exact version, you will be calling the latest supported API version.

	*/
	APIVersion *string
	/*ProjectID
	  projectId

	*/
	ProjectID *string
	/*Search
	  search

	*/
	Search *string
	/*SourceIds
	  sourceIds

	*/
	SourceIds []strfmt.UUID
	/*Types
	  types

	*/
	Types []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithTimeout(timeout time.Duration) *GetCatalogItemsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithContext(ctx context.Context) *GetCatalogItemsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithHTTPClient(client *http.Client) *GetCatalogItemsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarOrderby adds the dollarOrderby to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithDollarOrderby(dollarOrderby []string) *GetCatalogItemsUsingGETParams {
	o.SetDollarOrderby(dollarOrderby)
	return o
}

// SetDollarOrderby adds the dollarOrderby to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetDollarOrderby(dollarOrderby []string) {
	o.DollarOrderby = dollarOrderby
}

// WithDollarSkip adds the dollarSkip to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithDollarSkip(dollarSkip *int32) *GetCatalogItemsUsingGETParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetDollarSkip(dollarSkip *int32) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithDollarTop(dollarTop *int32) *GetCatalogItemsUsingGETParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetDollarTop(dollarTop *int32) {
	o.DollarTop = dollarTop
}

// WithAPIVersion adds the aPIVersion to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithAPIVersion(aPIVersion *string) *GetCatalogItemsUsingGETParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithProjectID adds the projectID to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithProjectID(projectID *string) *GetCatalogItemsUsingGETParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetProjectID(projectID *string) {
	o.ProjectID = projectID
}

// WithSearch adds the search to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithSearch(search *string) *GetCatalogItemsUsingGETParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetSearch(search *string) {
	o.Search = search
}

// WithSourceIds adds the sourceIds to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithSourceIds(sourceIds []strfmt.UUID) *GetCatalogItemsUsingGETParams {
	o.SetSourceIds(sourceIds)
	return o
}

// SetSourceIds adds the sourceIds to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetSourceIds(sourceIds []strfmt.UUID) {
	o.SourceIds = sourceIds
}

// WithTypes adds the types to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) WithTypes(types []string) *GetCatalogItemsUsingGETParams {
	o.SetTypes(types)
	return o
}

// SetTypes adds the types to the get catalog items using get params
func (o *GetCatalogItemsUsingGETParams) SetTypes(types []string) {
	o.Types = types
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogItemsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesDollarOrderby := o.DollarOrderby

	joinedDollarOrderby := swag.JoinByFormat(valuesDollarOrderby, "multi")
	// query array param $orderby
	if err := r.SetQueryParam("$orderby", joinedDollarOrderby...); err != nil {
		return err
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip int32
		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := swag.FormatInt32(qrDollarSkip)
		if qDollarSkip != "" {
			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}

	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int32
		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt32(qrDollarTop)
		if qDollarTop != "" {
			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}

	}

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string
		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {
			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}

	}

	if o.ProjectID != nil {

		// query param projectId
		var qrProjectID string
		if o.ProjectID != nil {
			qrProjectID = *o.ProjectID
		}
		qProjectID := qrProjectID
		if qProjectID != "" {
			if err := r.SetQueryParam("projectId", qProjectID); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	var valuesSourceIds []string
	for _, v := range o.SourceIds {
		valuesSourceIds = append(valuesSourceIds, v.String())
	}

	joinedSourceIds := swag.JoinByFormat(valuesSourceIds, "multi")
	// query array param sourceIds
	if err := r.SetQueryParam("sourceIds", joinedSourceIds...); err != nil {
		return err
	}

	valuesTypes := o.Types

	joinedTypes := swag.JoinByFormat(valuesTypes, "multi")
	// query array param types
	if err := r.SetQueryParam("types", joinedTypes...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
