// Code generated by go-swagger; DO NOT EDIT.

package network_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware/vra-sdk-go/pkg/models"
)

// GetNetworkProfileReader is a Reader for the GetNetworkProfile structure.
type GetNetworkProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNetworkProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetNetworkProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetNetworkProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkProfileOK creates a GetNetworkProfileOK with default headers values
func NewGetNetworkProfileOK() *GetNetworkProfileOK {
	return &GetNetworkProfileOK{}
}

/*GetNetworkProfileOK handles this case with default header values.

successful operation
*/
type GetNetworkProfileOK struct {
	Payload *models.NetworkProfile
}

func (o *GetNetworkProfileOK) Error() string {
	return fmt.Sprintf("[GET /iaas/api/network-profiles/{id}][%d] getNetworkProfileOK  %+v", 200, o.Payload)
}

func (o *GetNetworkProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNetworkProfileForbidden creates a GetNetworkProfileForbidden with default headers values
func NewGetNetworkProfileForbidden() *GetNetworkProfileForbidden {
	return &GetNetworkProfileForbidden{}
}

/*GetNetworkProfileForbidden handles this case with default header values.

Forbidden
*/
type GetNetworkProfileForbidden struct {
}

func (o *GetNetworkProfileForbidden) Error() string {
	return fmt.Sprintf("[GET /iaas/api/network-profiles/{id}][%d] getNetworkProfileForbidden ", 403)
}

func (o *GetNetworkProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetNetworkProfileNotFound creates a GetNetworkProfileNotFound with default headers values
func NewGetNetworkProfileNotFound() *GetNetworkProfileNotFound {
	return &GetNetworkProfileNotFound{}
}

/*GetNetworkProfileNotFound handles this case with default header values.

Not Found
*/
type GetNetworkProfileNotFound struct {
}

func (o *GetNetworkProfileNotFound) Error() string {
	return fmt.Sprintf("[GET /iaas/api/network-profiles/{id}][%d] getNetworkProfileNotFound ", 404)
}

func (o *GetNetworkProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
