// Code generated by go-swagger; DO NOT EDIT.

package compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// GetMachineSnapshotsReader is a Reader for the GetMachineSnapshots structure.
type GetMachineSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMachineSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMachineSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetMachineSnapshotsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMachineSnapshotsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMachineSnapshotsOK creates a GetMachineSnapshotsOK with default headers values
func NewGetMachineSnapshotsOK() *GetMachineSnapshotsOK {
	return &GetMachineSnapshotsOK{}
}

/*
GetMachineSnapshotsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetMachineSnapshotsOK struct {
	Payload []*models.Snapshot
}

// IsSuccess returns true when this get machine snapshots o k response has a 2xx status code
func (o *GetMachineSnapshotsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get machine snapshots o k response has a 3xx status code
func (o *GetMachineSnapshotsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get machine snapshots o k response has a 4xx status code
func (o *GetMachineSnapshotsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get machine snapshots o k response has a 5xx status code
func (o *GetMachineSnapshotsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get machine snapshots o k response a status code equal to that given
func (o *GetMachineSnapshotsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetMachineSnapshotsOK) Error() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsOK  %+v", 200, o.Payload)
}

func (o *GetMachineSnapshotsOK) String() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsOK  %+v", 200, o.Payload)
}

func (o *GetMachineSnapshotsOK) GetPayload() []*models.Snapshot {
	return o.Payload
}

func (o *GetMachineSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMachineSnapshotsForbidden creates a GetMachineSnapshotsForbidden with default headers values
func NewGetMachineSnapshotsForbidden() *GetMachineSnapshotsForbidden {
	return &GetMachineSnapshotsForbidden{}
}

/*
GetMachineSnapshotsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMachineSnapshotsForbidden struct {
	Payload *models.ServiceErrorResponse
}

// IsSuccess returns true when this get machine snapshots forbidden response has a 2xx status code
func (o *GetMachineSnapshotsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get machine snapshots forbidden response has a 3xx status code
func (o *GetMachineSnapshotsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get machine snapshots forbidden response has a 4xx status code
func (o *GetMachineSnapshotsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get machine snapshots forbidden response has a 5xx status code
func (o *GetMachineSnapshotsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get machine snapshots forbidden response a status code equal to that given
func (o *GetMachineSnapshotsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetMachineSnapshotsForbidden) Error() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsForbidden  %+v", 403, o.Payload)
}

func (o *GetMachineSnapshotsForbidden) String() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsForbidden  %+v", 403, o.Payload)
}

func (o *GetMachineSnapshotsForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *GetMachineSnapshotsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMachineSnapshotsNotFound creates a GetMachineSnapshotsNotFound with default headers values
func NewGetMachineSnapshotsNotFound() *GetMachineSnapshotsNotFound {
	return &GetMachineSnapshotsNotFound{}
}

/*
GetMachineSnapshotsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetMachineSnapshotsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get machine snapshots not found response has a 2xx status code
func (o *GetMachineSnapshotsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get machine snapshots not found response has a 3xx status code
func (o *GetMachineSnapshotsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get machine snapshots not found response has a 4xx status code
func (o *GetMachineSnapshotsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get machine snapshots not found response has a 5xx status code
func (o *GetMachineSnapshotsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get machine snapshots not found response a status code equal to that given
func (o *GetMachineSnapshotsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetMachineSnapshotsNotFound) Error() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsNotFound  %+v", 404, o.Payload)
}

func (o *GetMachineSnapshotsNotFound) String() string {
	return fmt.Sprintf("[GET /iaas/api/machines/{id}/snapshots][%d] getMachineSnapshotsNotFound  %+v", 404, o.Payload)
}

func (o *GetMachineSnapshotsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetMachineSnapshotsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
