// Code generated by go-swagger; DO NOT EDIT.

package compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// PowerOnMachineReader is a Reader for the PowerOnMachine structure.
type PowerOnMachineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PowerOnMachineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPowerOnMachineAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPowerOnMachineForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPowerOnMachineNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPowerOnMachineAccepted creates a PowerOnMachineAccepted with default headers values
func NewPowerOnMachineAccepted() *PowerOnMachineAccepted {
	return &PowerOnMachineAccepted{}
}

/*
PowerOnMachineAccepted describes a response with status code 202, with default header values.

successful operation
*/
type PowerOnMachineAccepted struct {
	Payload *models.RequestTracker
}

// IsSuccess returns true when this power on machine accepted response has a 2xx status code
func (o *PowerOnMachineAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this power on machine accepted response has a 3xx status code
func (o *PowerOnMachineAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this power on machine accepted response has a 4xx status code
func (o *PowerOnMachineAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this power on machine accepted response has a 5xx status code
func (o *PowerOnMachineAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this power on machine accepted response a status code equal to that given
func (o *PowerOnMachineAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *PowerOnMachineAccepted) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineAccepted  %+v", 202, o.Payload)
}

func (o *PowerOnMachineAccepted) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineAccepted  %+v", 202, o.Payload)
}

func (o *PowerOnMachineAccepted) GetPayload() *models.RequestTracker {
	return o.Payload
}

func (o *PowerOnMachineAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestTracker)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPowerOnMachineForbidden creates a PowerOnMachineForbidden with default headers values
func NewPowerOnMachineForbidden() *PowerOnMachineForbidden {
	return &PowerOnMachineForbidden{}
}

/*
PowerOnMachineForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PowerOnMachineForbidden struct {
	Payload *models.ServiceErrorResponse
}

// IsSuccess returns true when this power on machine forbidden response has a 2xx status code
func (o *PowerOnMachineForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this power on machine forbidden response has a 3xx status code
func (o *PowerOnMachineForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this power on machine forbidden response has a 4xx status code
func (o *PowerOnMachineForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this power on machine forbidden response has a 5xx status code
func (o *PowerOnMachineForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this power on machine forbidden response a status code equal to that given
func (o *PowerOnMachineForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *PowerOnMachineForbidden) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineForbidden  %+v", 403, o.Payload)
}

func (o *PowerOnMachineForbidden) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineForbidden  %+v", 403, o.Payload)
}

func (o *PowerOnMachineForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *PowerOnMachineForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPowerOnMachineNotFound creates a PowerOnMachineNotFound with default headers values
func NewPowerOnMachineNotFound() *PowerOnMachineNotFound {
	return &PowerOnMachineNotFound{}
}

/*
PowerOnMachineNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PowerOnMachineNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this power on machine not found response has a 2xx status code
func (o *PowerOnMachineNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this power on machine not found response has a 3xx status code
func (o *PowerOnMachineNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this power on machine not found response has a 4xx status code
func (o *PowerOnMachineNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this power on machine not found response has a 5xx status code
func (o *PowerOnMachineNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this power on machine not found response a status code equal to that given
func (o *PowerOnMachineNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *PowerOnMachineNotFound) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineNotFound  %+v", 404, o.Payload)
}

func (o *PowerOnMachineNotFound) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/power-on][%d] powerOnMachineNotFound  %+v", 404, o.Payload)
}

func (o *PowerOnMachineNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PowerOnMachineNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
