// Code generated by go-swagger; DO NOT EDIT.

package compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// ResizeMachineReader is a Reader for the ResizeMachine structure.
type ResizeMachineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResizeMachineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewResizeMachineAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewResizeMachineForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewResizeMachineNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewResizeMachineAccepted creates a ResizeMachineAccepted with default headers values
func NewResizeMachineAccepted() *ResizeMachineAccepted {
	return &ResizeMachineAccepted{}
}

/*
ResizeMachineAccepted describes a response with status code 202, with default header values.

successful operation
*/
type ResizeMachineAccepted struct {
	Payload *models.RequestTracker
}

// IsSuccess returns true when this resize machine accepted response has a 2xx status code
func (o *ResizeMachineAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this resize machine accepted response has a 3xx status code
func (o *ResizeMachineAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resize machine accepted response has a 4xx status code
func (o *ResizeMachineAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this resize machine accepted response has a 5xx status code
func (o *ResizeMachineAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this resize machine accepted response a status code equal to that given
func (o *ResizeMachineAccepted) IsCode(code int) bool {
	return code == 202
}

func (o *ResizeMachineAccepted) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineAccepted  %+v", 202, o.Payload)
}

func (o *ResizeMachineAccepted) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineAccepted  %+v", 202, o.Payload)
}

func (o *ResizeMachineAccepted) GetPayload() *models.RequestTracker {
	return o.Payload
}

func (o *ResizeMachineAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestTracker)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResizeMachineForbidden creates a ResizeMachineForbidden with default headers values
func NewResizeMachineForbidden() *ResizeMachineForbidden {
	return &ResizeMachineForbidden{}
}

/*
ResizeMachineForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ResizeMachineForbidden struct {
	Payload *models.ServiceErrorResponse
}

// IsSuccess returns true when this resize machine forbidden response has a 2xx status code
func (o *ResizeMachineForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resize machine forbidden response has a 3xx status code
func (o *ResizeMachineForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resize machine forbidden response has a 4xx status code
func (o *ResizeMachineForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this resize machine forbidden response has a 5xx status code
func (o *ResizeMachineForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this resize machine forbidden response a status code equal to that given
func (o *ResizeMachineForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *ResizeMachineForbidden) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineForbidden  %+v", 403, o.Payload)
}

func (o *ResizeMachineForbidden) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineForbidden  %+v", 403, o.Payload)
}

func (o *ResizeMachineForbidden) GetPayload() *models.ServiceErrorResponse {
	return o.Payload
}

func (o *ResizeMachineForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewResizeMachineNotFound creates a ResizeMachineNotFound with default headers values
func NewResizeMachineNotFound() *ResizeMachineNotFound {
	return &ResizeMachineNotFound{}
}

/*
ResizeMachineNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ResizeMachineNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this resize machine not found response has a 2xx status code
func (o *ResizeMachineNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resize machine not found response has a 3xx status code
func (o *ResizeMachineNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resize machine not found response has a 4xx status code
func (o *ResizeMachineNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this resize machine not found response has a 5xx status code
func (o *ResizeMachineNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this resize machine not found response a status code equal to that given
func (o *ResizeMachineNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ResizeMachineNotFound) Error() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineNotFound  %+v", 404, o.Payload)
}

func (o *ResizeMachineNotFound) String() string {
	return fmt.Sprintf("[POST /iaas/api/machines/{id}/operations/resize][%d] resizeMachineNotFound  %+v", 404, o.Payload)
}

func (o *ResizeMachineNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ResizeMachineNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
