// Code generated by go-swagger; DO NOT EDIT.

package fabric_compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/vmware/vra-sdk-go/pkg/models"
)

// NewUpdateFabricComputeParams creates a new UpdateFabricComputeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateFabricComputeParams() *UpdateFabricComputeParams {
	return &UpdateFabricComputeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFabricComputeParamsWithTimeout creates a new UpdateFabricComputeParams object
// with the ability to set a timeout on a request.
func NewUpdateFabricComputeParamsWithTimeout(timeout time.Duration) *UpdateFabricComputeParams {
	return &UpdateFabricComputeParams{
		timeout: timeout,
	}
}

// NewUpdateFabricComputeParamsWithContext creates a new UpdateFabricComputeParams object
// with the ability to set a context for a request.
func NewUpdateFabricComputeParamsWithContext(ctx context.Context) *UpdateFabricComputeParams {
	return &UpdateFabricComputeParams{
		Context: ctx,
	}
}

// NewUpdateFabricComputeParamsWithHTTPClient creates a new UpdateFabricComputeParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateFabricComputeParamsWithHTTPClient(client *http.Client) *UpdateFabricComputeParams {
	return &UpdateFabricComputeParams{
		HTTPClient: client,
	}
}

/* UpdateFabricComputeParams contains all the parameters to send to the API endpoint
   for the update fabric compute operation.

   Typically these are written to a http.Request.
*/
type UpdateFabricComputeParams struct {

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information refer to /iaas/api/about
	*/
	APIVersion *string

	/* Body.

	   Fabric Compute Specification
	*/
	Body *models.FabricComputeSpecification

	/* ID.

	   The ID of the Fabric Compute.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update fabric compute params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFabricComputeParams) WithDefaults() *UpdateFabricComputeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update fabric compute params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFabricComputeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update fabric compute params
func (o *UpdateFabricComputeParams) WithTimeout(timeout time.Duration) *UpdateFabricComputeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update fabric compute params
func (o *UpdateFabricComputeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update fabric compute params
func (o *UpdateFabricComputeParams) WithContext(ctx context.Context) *UpdateFabricComputeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update fabric compute params
func (o *UpdateFabricComputeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update fabric compute params
func (o *UpdateFabricComputeParams) WithHTTPClient(client *http.Client) *UpdateFabricComputeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update fabric compute params
func (o *UpdateFabricComputeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the update fabric compute params
func (o *UpdateFabricComputeParams) WithAPIVersion(aPIVersion *string) *UpdateFabricComputeParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the update fabric compute params
func (o *UpdateFabricComputeParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the update fabric compute params
func (o *UpdateFabricComputeParams) WithBody(body *models.FabricComputeSpecification) *UpdateFabricComputeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update fabric compute params
func (o *UpdateFabricComputeParams) SetBody(body *models.FabricComputeSpecification) {
	o.Body = body
}

// WithID adds the id to the update fabric compute params
func (o *UpdateFabricComputeParams) WithID(id string) *UpdateFabricComputeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update fabric compute params
func (o *UpdateFabricComputeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFabricComputeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
