// Code generated by go-swagger; DO NOT EDIT.

package blueprint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/vmware/vra-sdk-go/pkg/models"
)

// CreateBlueprintUsingPOSTReader is a Reader for the CreateBlueprintUsingPOST structure.
type CreateBlueprintUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBlueprintUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateBlueprintUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewCreateBlueprintUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewCreateBlueprintUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateBlueprintUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateBlueprintUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateBlueprintUsingPOSTOK creates a CreateBlueprintUsingPOSTOK with default headers values
func NewCreateBlueprintUsingPOSTOK() *CreateBlueprintUsingPOSTOK {
	return &CreateBlueprintUsingPOSTOK{}
}

/*CreateBlueprintUsingPOSTOK handles this case with default header values.

OK
*/
type CreateBlueprintUsingPOSTOK struct {
	Payload *models.BlueprintLinkResponse
}

func (o *CreateBlueprintUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /blueprint/api/blueprints][%d] createBlueprintUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateBlueprintUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BlueprintLinkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBlueprintUsingPOSTCreated creates a CreateBlueprintUsingPOSTCreated with default headers values
func NewCreateBlueprintUsingPOSTCreated() *CreateBlueprintUsingPOSTCreated {
	return &CreateBlueprintUsingPOSTCreated{}
}

/*CreateBlueprintUsingPOSTCreated handles this case with default header values.

Created
*/
type CreateBlueprintUsingPOSTCreated struct {
}

func (o *CreateBlueprintUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /blueprint/api/blueprints][%d] createBlueprintUsingPOSTCreated ", 201)
}

func (o *CreateBlueprintUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBlueprintUsingPOSTUnauthorized creates a CreateBlueprintUsingPOSTUnauthorized with default headers values
func NewCreateBlueprintUsingPOSTUnauthorized() *CreateBlueprintUsingPOSTUnauthorized {
	return &CreateBlueprintUsingPOSTUnauthorized{}
}

/*CreateBlueprintUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateBlueprintUsingPOSTUnauthorized struct {
}

func (o *CreateBlueprintUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /blueprint/api/blueprints][%d] createBlueprintUsingPOSTUnauthorized ", 401)
}

func (o *CreateBlueprintUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBlueprintUsingPOSTForbidden creates a CreateBlueprintUsingPOSTForbidden with default headers values
func NewCreateBlueprintUsingPOSTForbidden() *CreateBlueprintUsingPOSTForbidden {
	return &CreateBlueprintUsingPOSTForbidden{}
}

/*CreateBlueprintUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateBlueprintUsingPOSTForbidden struct {
}

func (o *CreateBlueprintUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /blueprint/api/blueprints][%d] createBlueprintUsingPOSTForbidden ", 403)
}

func (o *CreateBlueprintUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateBlueprintUsingPOSTNotFound creates a CreateBlueprintUsingPOSTNotFound with default headers values
func NewCreateBlueprintUsingPOSTNotFound() *CreateBlueprintUsingPOSTNotFound {
	return &CreateBlueprintUsingPOSTNotFound{}
}

/*CreateBlueprintUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type CreateBlueprintUsingPOSTNotFound struct {
}

func (o *CreateBlueprintUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /blueprint/api/blueprints][%d] createBlueprintUsingPOSTNotFound ", 404)
}

func (o *CreateBlueprintUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
