// Code generated by go-swagger; DO NOT EDIT.

package blueprint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlueprintVersionUsingGETParams creates a new GetBlueprintVersionUsingGETParams object
// with the default values initialized.
func NewGetBlueprintVersionUsingGETParams() *GetBlueprintVersionUsingGETParams {
	var ()
	return &GetBlueprintVersionUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlueprintVersionUsingGETParamsWithTimeout creates a new GetBlueprintVersionUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBlueprintVersionUsingGETParamsWithTimeout(timeout time.Duration) *GetBlueprintVersionUsingGETParams {
	var ()
	return &GetBlueprintVersionUsingGETParams{

		timeout: timeout,
	}
}

// NewGetBlueprintVersionUsingGETParamsWithContext creates a new GetBlueprintVersionUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBlueprintVersionUsingGETParamsWithContext(ctx context.Context) *GetBlueprintVersionUsingGETParams {
	var ()
	return &GetBlueprintVersionUsingGETParams{

		Context: ctx,
	}
}

// NewGetBlueprintVersionUsingGETParamsWithHTTPClient creates a new GetBlueprintVersionUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBlueprintVersionUsingGETParamsWithHTTPClient(client *http.Client) *GetBlueprintVersionUsingGETParams {
	var ()
	return &GetBlueprintVersionUsingGETParams{
		HTTPClient: client,
	}
}

/*GetBlueprintVersionUsingGETParams contains all the parameters to send to the API endpoint
for the get blueprint version using g e t operation typically these are written to a http.Request
*/
type GetBlueprintVersionUsingGETParams struct {

	/*BlueprintID
	  blueprintId

	*/
	BlueprintID strfmt.UUID
	/*Version
	  version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) WithTimeout(timeout time.Duration) *GetBlueprintVersionUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) WithContext(ctx context.Context) *GetBlueprintVersionUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) WithHTTPClient(client *http.Client) *GetBlueprintVersionUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlueprintID adds the blueprintID to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) WithBlueprintID(blueprintID strfmt.UUID) *GetBlueprintVersionUsingGETParams {
	o.SetBlueprintID(blueprintID)
	return o
}

// SetBlueprintID adds the blueprintId to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) SetBlueprintID(blueprintID strfmt.UUID) {
	o.BlueprintID = blueprintID
}

// WithVersion adds the version to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) WithVersion(version string) *GetBlueprintVersionUsingGETParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get blueprint version using get params
func (o *GetBlueprintVersionUsingGETParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlueprintVersionUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param blueprintId
	if err := r.SetPathParam("blueprintId", o.BlueprintID.String()); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
