// Code generated by go-swagger; DO NOT EDIT.

package security_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSecurityGroupsParams creates a new GetSecurityGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSecurityGroupsParams() *GetSecurityGroupsParams {
	return &GetSecurityGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSecurityGroupsParamsWithTimeout creates a new GetSecurityGroupsParams object
// with the ability to set a timeout on a request.
func NewGetSecurityGroupsParamsWithTimeout(timeout time.Duration) *GetSecurityGroupsParams {
	return &GetSecurityGroupsParams{
		timeout: timeout,
	}
}

// NewGetSecurityGroupsParamsWithContext creates a new GetSecurityGroupsParams object
// with the ability to set a context for a request.
func NewGetSecurityGroupsParamsWithContext(ctx context.Context) *GetSecurityGroupsParams {
	return &GetSecurityGroupsParams{
		Context: ctx,
	}
}

// NewGetSecurityGroupsParamsWithHTTPClient creates a new GetSecurityGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSecurityGroupsParamsWithHTTPClient(client *http.Client) *GetSecurityGroupsParams {
	return &GetSecurityGroupsParams{
		HTTPClient: client,
	}
}

/* GetSecurityGroupsParams contains all the parameters to send to the API endpoint
   for the get security groups operation.

   Typically these are written to a http.Request.
*/
type GetSecurityGroupsParams struct {

	/* DollarFilter.

	   Add a filter to return limited results
	*/
	DollarFilter *string

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information refer to /iaas/api/about
	*/
	APIVersion *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get security groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecurityGroupsParams) WithDefaults() *GetSecurityGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get security groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSecurityGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get security groups params
func (o *GetSecurityGroupsParams) WithTimeout(timeout time.Duration) *GetSecurityGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get security groups params
func (o *GetSecurityGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get security groups params
func (o *GetSecurityGroupsParams) WithContext(ctx context.Context) *GetSecurityGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get security groups params
func (o *GetSecurityGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get security groups params
func (o *GetSecurityGroupsParams) WithHTTPClient(client *http.Client) *GetSecurityGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get security groups params
func (o *GetSecurityGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the get security groups params
func (o *GetSecurityGroupsParams) WithDollarFilter(dollarFilter *string) *GetSecurityGroupsParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the get security groups params
func (o *GetSecurityGroupsParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithAPIVersion adds the aPIVersion to the get security groups params
func (o *GetSecurityGroupsParams) WithAPIVersion(aPIVersion *string) *GetSecurityGroupsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get security groups params
func (o *GetSecurityGroupsParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WriteToRequest writes these params to a swagger request
func (o *GetSecurityGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
