// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectResourceMetadataParams creates a new GetProjectResourceMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectResourceMetadataParams() *GetProjectResourceMetadataParams {
	return &GetProjectResourceMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectResourceMetadataParamsWithTimeout creates a new GetProjectResourceMetadataParams object
// with the ability to set a timeout on a request.
func NewGetProjectResourceMetadataParamsWithTimeout(timeout time.Duration) *GetProjectResourceMetadataParams {
	return &GetProjectResourceMetadataParams{
		timeout: timeout,
	}
}

// NewGetProjectResourceMetadataParamsWithContext creates a new GetProjectResourceMetadataParams object
// with the ability to set a context for a request.
func NewGetProjectResourceMetadataParamsWithContext(ctx context.Context) *GetProjectResourceMetadataParams {
	return &GetProjectResourceMetadataParams{
		Context: ctx,
	}
}

// NewGetProjectResourceMetadataParamsWithHTTPClient creates a new GetProjectResourceMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectResourceMetadataParamsWithHTTPClient(client *http.Client) *GetProjectResourceMetadataParams {
	return &GetProjectResourceMetadataParams{
		HTTPClient: client,
	}
}

/*
GetProjectResourceMetadataParams contains all the parameters to send to the API endpoint

	for the get project resource metadata operation.

	Typically these are written to a http.Request.
*/
type GetProjectResourceMetadataParams struct {

	/* APIVersion.

	   The version of the API in yyyy-MM-dd format (UTC). For versioning information refer to /iaas/api/about
	*/
	APIVersion *string

	/* ID.

	   The ID of the project.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project resource metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectResourceMetadataParams) WithDefaults() *GetProjectResourceMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project resource metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectResourceMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) WithTimeout(timeout time.Duration) *GetProjectResourceMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) WithContext(ctx context.Context) *GetProjectResourceMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) WithHTTPClient(client *http.Client) *GetProjectResourceMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) WithAPIVersion(aPIVersion *string) *GetProjectResourceMetadataParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithID adds the id to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) WithID(id string) *GetProjectResourceMetadataParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project resource metadata params
func (o *GetProjectResourceMetadataParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectResourceMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// query param apiVersion
		var qrAPIVersion string

		if o.APIVersion != nil {
			qrAPIVersion = *o.APIVersion
		}
		qAPIVersion := qrAPIVersion
		if qAPIVersion != "" {

			if err := r.SetQueryParam("apiVersion", qAPIVersion); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
